### ISSUE TITLE
how to use visualize_cv.py

### ISSUE THREAD

**Issue by 5kejun** [markjay4k/Mask-RCNN-series#5]
First of all thank you for your creative work, but how do you use the visualize_cv.py file? Put it in Mattport's Mask_RCNN_master folder and replace the visualize.py file? And finally run demo.ipynb? I donot know if it is necessary to modify the demo.ipynb file to achieve the goal of camera stream processing.

**Comment by markjay4k** [comment]
I made a video explaining how to run that file

https://www.youtube.com/watch?v=lLM8oAsi32g

**Comment by 5kejun** [comment]
Pretty cool thanks a lot dude. Just run the visualize_cv.py file by python IDE such as IDLE  and so on.

**Comment by AshleyRoth** [comment]
@markjay4k Hi Mark! I download your visualize_cv.py, and when i try to run with IDLE or terminal i get a error
```
  File "visualize_cv.py", line 59, in <module>
    import coco
ModuleNotFoundError: No module named 'coco'
```
I download pythoncoco tools, install. error still goes out...
Help me solve the problem .. I want to get a video through the camera ..Please

**Comment by markjay4k** [comment]
you will need to install pycocotools. make sure you have visual c++ build tools installed. you can refer to the install instructions in the notebook I made, or you can check the pycocotools repo as well (link is in the notebook).

**Comment by Adithia99** [comment]
how to visualize that with fps? i can visualize that but i need the fps too ? do u have codes that include FPS in there?
